### ISSUE TITLE
Complete Guide: Using .env Files with Spring Boot and Docker - Step by Step

### ISSUE THREAD

**Issue by harshal5-dev** [harshal5-dev/cloud-kart#1]
# Complete Guide: Using .env Files with Spring Boot and Docker

## Overview
This guide provides step-by-step instructions for integrating `.env` files with your Cloud Kart Spring Boot microservices and Docker containers.

### Step 1: Create Project Structure
```bash
# Your project structure should look like this:
cloud-kart/
├── .env.example                 # Template file (committed to git)
├── .env                        # Actual environment file (NOT committed)
├── .gitignore                  # Contains .env exclusions
├── config-server/
│   ├── src/main/resources/
│   │   ├── application.yml     # Spring Boot configuration
│   │   └── application-dev.yml # Development profile
│   └── pom.xml
└── docker-compose.yml
```

#### Create .env.example (Template)
```bash name=.env.example
# ==============================================================================
# CLOUD KART - ENVIRONMENT CONFIGURATION TEMPLATE
# ==============================================================================
# Copy this file to .env and update values for your environment

# Application Configuration
SPRING_PROFILES_ACTIVE=dev
APPLICATION_NAME=cloud-kart
APPLICATION_VERSION=1.0.0-SNAPSHOT

# Server Configuration
CONFIG_SERVER_PORT=8888
EUREKA_SERVER_PORT=8761
API_GATEWAY_PORT=8080

# Database Configuration
DB_HOST=localhost
DB_PORT=5432
DB_NAME=cloudkart
DB_USERNAME=cloudkart_user
DB_PASSWORD=your_db_password_here

# Redis Configuration
REDIS_HOST=localhost
REDIS_PORT=6379
REDIS_PASSWORD=your_redis_password_here

# Security Configuration
JWT_SECRET_KEY=your_jwt_secret_key_here
JWT_EXPIRATION=86400000

# External Services
STRIPE_SECRET_KEY=sk_test_your_stripe_key_here
SMTP_USERNAME=your_email@gmail.com
SMTP_PASSWORD=your_email_password_here

# Monitoring
ZIPKIN_BASE_URL=http://localhost:9411
PROMETHEUS_PORT=9090

# Docker Configuration
DOCKER_REGISTRY=docker.io
DOCKER_USERNAME=harshal5dev
DOCKER_IMAGE_TAG=latest
```

#### Create Your Actual .env File
```bash
# Copy the template and customize
cp .env.example .env

# Edit with your real values
nano .env
```

```bash name=.env
# Your actual .env file with real values
SPRING_PROFILES_ACTIVE=dev
APPLICATION_NAME=cloud-kart
APPLICATION_VERSION=1.0.0-SNAPSHOT

# Server Configuration
CONFIG_SERVER_PORT=8888
EUREKA_SERVER_PORT=8761
API_GATEWAY_PORT=8080

# Database Configuration (Real values)
DB_HOST=localhost
DB_PORT=5432
DB_NAME=cloudkart_dev
DB_USERNAME=postgres
DB_PASSWORD=myRealPassword123

# Redis Configuration
REDIS_HOST=localhost
REDIS_PORT=6379
REDIS_PASSWORD=myRedisPassword456

# Security Configuration
JWT_SECRET_KEY=myActualJwtSecretKey2025CloudKartVeryLongAndSecure
JWT_EXPIRATION=86400000

# External Services
STRIPE_SECRET_KEY=sk_test_51Hx...your_actual_stripe_key
SMTP_USERNAME=noreply@cloudkart.com
SMTP_PASSWORD=your_actual_email_password

# Monitoring
ZIPKIN_BASE_URL=http://localhost:9411
PROMETHEUS_PORT=9090

# Docker Configuration
DOCKER_REGISTRY=docker.io
DOCKER_USERNAME=harshal5dev
DOCKER_IMAGE_TAG=1.0.0-SNAPSHOT
```

### Step 3: Update .gitignore
```bash name=.gitignore
# Environment files - NEVER commit these
.env
.env.local
.env.*.local
.env.development
.env.production
.env.staging

# BUT keep the template
!.env.example

# Maven
target/
*.jar
*.war

# IDE
.idea/
*.iml
.vscode/

# Logs
logs/
*.log

# Docker
.docker/
```

### Step 4: Add Dependencies to pom.xml

```xml name=pom.xml
<dependencies>
    <!-- Spring Boot Configuration Processor -->
    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-configuration-processor</artifactId>
        <optional>true</optional>
    </dependency>
    
    <!-- For environment variable validation -->
    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-validation</artifactId>
    </dependency>
</dependencies>
```

### Step 5: Configure application.yml to Use Environment Variables

```yaml name=src/main/resources/application.yml
# Main application configuration
spring:
  application:
    name: ${APPLICATION_NAME:config-server}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

server:
  port: ${CONFIG_SERVER_PORT:8888}

# Logging configuration
logging:
  level:
    com.cloudkart: ${LOG_LEVEL:INFO}
    org.springframework.cloud.config: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics
  endpoint:
    health:
      show-details: always

---
# Development profile
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:cloudkart_dev}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    timeout: 2000ms

# JWT Configuration
jwt:
  secret: ${JWT_SECRET_KEY:defaultSecretKey}
  expiration: ${JWT_EXPIRATION:86400000}

# External Services
stripe:
  secret-key: ${STRIPE_SECRET_KEY:}

mail:
  host: smtp.gmail.com
  port: 587
  username: ${SMTP_USERNAME:}
  password: ${SMTP_PASSWORD:}

---
# Production profile
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    com.cloudkart: INFO
    org.springframework.cloud.config: WARN
```

### Step 6: Create Configuration Classes

```java name=src/main/java/com/cloudkart/config/AppConfig.java
package com.cloudkart.config;

import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.context.annotation.Configuration;
import org.springframework.validation.annotation.Validated;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.Data;

@Configuration
@ConfigurationProperties(prefix = "app")
@Validated
@Data
public class AppConfig {
    
    @NotBlank(message = "Application name is required")
    private String name;
    
    @NotBlank(message = "Application version is required")
    private String version;
    
    @NotNull(message = "Server port is required")
    private Integer port;
}
```

```java name=src/main/java/com/cloudkart/config/DatabaseConfig.java
package com.cloudkart.config;

import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.context.annotation.Configuration;
import org.springframework.validation.annotation.Validated;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import lombok.Data;

@Configuration
@ConfigurationProperties(prefix = "spring.datasource")
@Validated
@Data
public class DatabaseConfig {
    
    @NotBlank(message = "Database URL is required")
    private String url;
    
    @NotBlank(message = "Database username is required")
    private String username;
    
    @NotBlank(message = "Database password is required")
    private String password;
    
    // Hikari connection pool settings
    private Hikari hikari = new Hikari();
    
    @Data
    public static class Hikari {
        @Min(value = 1, message = "Maximum pool size must be at least 1")
        @Max(value = 50, message = "Maximum pool size cannot exceed 50")
        private Integer maximumPoolSize = 10;
        
        @Min(value = 0, message = "Minimum idle cannot be negative")
        private Integer minimumIdle = 5;
        
        private Long connectionTimeout = 30000L;
        private Long idleTimeout = 600000L;
        private Long maxLifetime = 1800000L;
    }
}
```

```java name=src/main/java/com/cloudkart/config/JwtConfig.java
package com.cloudkart.config;

import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.context.annotation.Configuration;
import org.springframework.validation.annotation.Validated;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Min;
import lombok.Data;

@Configuration
@ConfigurationProperties(prefix = "jwt")
@Validated
@Data
public class JwtConfig {
    
    @NotBlank(message = "JWT secret key is required")
    private String secret;
    
    @Min(value = 3600000, message = "JWT expiration must be at least 1 hour")
    private Long expiration;
}
```

### Step 7: Load Environment Variables in Main Application

```java name=src/main/java/com/cloudkart/ConfigServerApplication.java
package com.cloudkart;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.cloud.config.server.EnableConfigServer;
import org.springframework.cloud.netflix.eureka.EnableEurekaClient;

import com.cloudkart.config.AppConfig;
import com.cloudkart.config.DatabaseConfig;
import com.cloudkart.config.JwtConfig;

import io.github.cdimascio.dotenv.Dotenv;

@SpringBootApplication
@EnableConfigServer
@EnableEurekaClient
@EnableConfigurationProperties({AppConfig.class, DatabaseConfig.class, JwtConfig.class})
public class ConfigServerApplication {

    public static void main(String[] args) {
        // Load .env file (for development)
        if (isLocalEnvironment()) {
            loadDotenv();
        }
        
        SpringApplication.run(ConfigServerApplication.class, args);
    }
    
    private static void loadDotenv() {
        try {
            Dotenv dotenv = Dotenv.configure()
                .filename(".env")  // Look for .env file
                .ignoreIfMalformed()
                .ignoreIfMissing()
                .load();
            
            // Set system properties from .env file
            dotenv.entries().forEach(entry -> {
                System.setProperty(entry.getKey(), entry.getValue());
            });
            
            System.out.println("✅ Environment variables loaded from .env file");
        } catch (Exception e) {
            System.err.println("⚠️  Could not load .env file: " + e.getMessage());
            System.err.println("Continuing with system environment variables...");
        }
    }
    
    private static boolean isLocalEnvironment() {
        String profile = System.getProperty("spring.profiles.active", 
                         System.getenv("SPRING_PROFILES_ACTIVE"));
        return profile == null || "dev".equals(profile) || "local".equals(profile);
    }
}
```

### Step 8: Add dotenv-java Dependency

```xml name=pom.xml
<dependency>
    <groupId>io.github.cdimascio</groupId>
    <artifactId>dotenv-java</artifactId>
    <version>3.0.0</version>
</dependency>
```

### Step 9: Alternative: Using Spring Boot's Built-in Environment Loading

```java name=src/main/java/com/cloudkart/config/EnvironmentConfig.java
package com.cloudkart.config;

import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.PropertySource;
import org.springframework.core.env.Environment;

import jakarta.annotation.PostConstruct;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;

@Configuration
@PropertySource(value = "file:.env", ignoreResourceNotFound = true)
@RequiredArgsConstructor
@Slf4j
public class EnvironmentConfig {
    
    private final Environment environment;
    
    @PostConstruct
    public void validateEnvironment() {
        log.info("🚀 Starting Cloud Kart Config Server");
        log.info("Environment: {}", environment.getProperty("SPRING_PROFILES_ACTIVE", "default"));
        log.info("Server Port: {}", environment.getProperty("CONFIG_SERVER_PORT", "8888"));
        log.info("Database Host: {}", environment.getProperty("DB_HOST", "localhost"));
        
        // Validate critical environment variables
        validateRequiredProperty("JWT_SECRET_KEY", "JWT secret key is required for security");
        validateRequiredProperty("DB_PASSWORD", "Database password is required");
        
        log.info("✅ Environment validation completed");
    }
    
    private void validateRequiredProperty(String propertyName, String errorMessage) {
        String value = environment.getProperty(propertyName);
        if (value == null || value.trim().isEmpty()) {
            log.error("❌ {}: {}", errorMessage, propertyName);
            throw new IllegalStateException(errorMessage + ": " + propertyName);
        }
    }
}
```

### Step 10: Create Dockerfile

```dockerfile name=Dockerfile
FROM eclipse-temurin:21-jre-alpine

# Set working directory
WORKDIR /app

# Create non-root user for security
RUN addgroup -g 1001 -S appgroup && \
    adduser -u 1001 -S appuser -G appgroup

# Copy the JAR file
COPY target/config-server-*.jar app.jar

# Change ownership to non-root user
RUN chown -R appuser:appgroup /app

# Switch to non-root user
USER appuser

# Expose port (will be overridden by environment variable)
EXPOSE ${CONFIG_SERVER_PORT:-8888}

# Health check
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
    CMD wget --no-verbose --tries=1 --spider http://localhost:${CONFIG_SERVER_PORT:-8888}/actuator/health || exit 1

# Environment variables (defaults)
ENV SPRING_PROFILES_ACTIVE=docker
ENV CONFIG_SERVER_PORT=8888
ENV JAVA_OPTS="-Xmx512m -Xms256m"

# Run the application
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar app.jar"]
```

### Step 11: Create Docker Compose Configuration

```yaml name=docker-compose.yml
version: '3.8'

services:
  config-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cloudkart-config-server
    ports:
      - "${CONFIG_SERVER_PORT:-8888}:${CONFIG_SERVER_PORT:-8888}"
    environment:
      # Spring Boot Configuration
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-docker}
      - CONFIG_SERVER_PORT=${CONFIG_SERVER_PORT:-8888}
      
      # Database Configuration
      - DB_HOST=${DB_HOST:-postgres}
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME:-cloudkart}
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_PASSWORD=${DB_PASSWORD}
      
      # Redis Configuration
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      
      # Security Configuration
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_EXPIRATION=${JWT_EXPIRATION:-86400000}
      
      # External Services
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      
      # Monitoring
      - ZIPKIN_BASE_URL=${ZIPKIN_BASE_URL:-http://zipkin:9411}
      
      # JVM Options
      - JAVA_OPTS=${JAVA_OPTS:--Xmx512m -Xms256m}
    env_file:
      - .env  # Load all variables from .env file
    depends_on:
      - postgres
      - redis
    networks:
      - cloudkart-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:${CONFIG_SERVER_PORT:-8888}/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgres:
    image: postgres:15-alpine
    container_name: cloudkart-postgres
    environment:
      - POSTGRES_DB=${DB_NAME:-cloudkart}
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - cloudkart-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: cloudkart-redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    networks:
      - cloudkart-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  cloudkart-network:
    driver: bridge
```

#### Development Override
```yaml name=docker-compose.override.yml
version: '3.8'

services:
  config-server:
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DEBUG_MODE=true
    volumes:
      - ./logs:/app/logs
    ports:
      - "5005:5005"  # Debug port
    command: ["sh", "-c", "java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 $JAVA_OPTS -jar app.jar"]

  postgres:
    environment:
      - POSTGRES_DB=cloudkart_dev
    ports:
      - "5432:5432"
```

#### Production Configuration
```yaml name=docker-compose.prod.yml
version: '3.8'

services:
  config-server:
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xmx1g -Xms512m -XX:+UseG1GC
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
    restart: always

  postgres:
    environment:
      - POSTGRES_DB=cloudkart_prod
    volumes:
      - /var/lib/cloudkart/postgres:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
```

### Step 13: Local Development Setup

```bash
# 1. Set up environment
cp .env.example .env
nano .env  # Edit with your values

# 2. Run with Maven (loads .env automatically)
mvn clean compile
mvn spring-boot:run

# 3. Or run with environment variables
export $(grep -v '^#' .env | xargs)
mvn spring-boot:run

# 4. Or run JAR with environment
java -jar target/config-server-1.0.0-SNAPSHOT.jar
```

### Step 14: Docker Development Setup

```bash
# 1. Build and run with Docker Compose
docker-compose up --build

# 2. Run in development mode
docker-compose -f docker-compose.yml -f docker-compose.override.yml up --build

# 3. Run specific services
docker-compose up postgres redis
mvn spring-boot:run  # Run Spring Boot locally, use containerized databases
```

### Step 15: Production Deployment

```bash
# 1. Create production environment file
cp .env.example .env.prod
nano .env.prod  # Edit with production values

# 2. Deploy to production
docker-compose -f docker-compose.yml -f docker-compose.prod.yml --env-file .env.prod up -d

# 3. Monitor logs
docker-compose logs -f config-server

# 4. Health check
curl http://localhost:8888/actuator/health
```

### Step 16: Validation Scripts

```bash name=scripts/validate-env.sh
#!/bin/bash
# Environment validation script

set -e

echo "🔍 Validating Cloud Kart Environment Configuration..."

# Check if .env file exists
if [ ! -f .env ]; then
    echo "❌ .env file not found. Please copy .env.example to .env and configure it."
    exit 1
fi

# Load .env file
export $(grep -v '^#' .env | xargs)

# Required environment variables
REQUIRED_VARS=(
    "CONFIG_SERVER_PORT"
    "DB_HOST"
    "DB_USERNAME"
    "DB_PASSWORD"
    "JWT_SECRET_KEY"
)

# Optional but recommended variables
RECOMMENDED_VARS=(
    "REDIS_HOST"
    "STRIPE_SECRET_KEY"
    "SMTP_USERNAME"
)

# Validate required variables
echo "📋 Checking required variables..."
for var in "${REQUIRED_VARS[@]}"; do
    if [ -z "${!var}" ]; then
        echo "❌ Missing required variable: $var"
        exit 1
    else
        echo "✅ $var is set"
    fi
done

# Check recommended variables
echo "📋 Checking recommended variables..."
for var in "${RECOMMENDED_VARS[@]}"; do
    if [ -z "${!var}" ]; then
        echo "⚠️  Recommended variable not set: $var"
    else
        echo "✅ $var is set"
    fi
done

# Validate ports
echo "📋 Checking port configurations..."
if ! [[ "$CONFIG_SERVER_PORT" =~ ^[0-9]+$ ]] || [ "$CONFIG_SERVER_PORT" -lt 1024 ] || [ "$CONFIG_SERVER_PORT" -gt 65535 ]; then
    echo "❌ CONFIG_SERVER_PORT must be a number between 1024 and 65535"
    exit 1
fi

# Validate JWT secret length
if [ ${#JWT_SECRET_KEY} -lt 32 ]; then
    echo "❌ JWT_SECRET_KEY must be at least 32 characters long"
    exit 1
fi

echo "🎉 Environment validation completed successfully!"
echo "🚀 You can now run: mvn spring-boot:run or docker-compose up"
```

```bash name=scripts/setup-dev.sh
#!/bin/bash
# Development setup script

set -e

echo "🚀 Setting up Cloud Kart development environment..."

# Create .env from template if it doesn't exist
if [ ! -f .env ]; then
    echo "📄 Creating .env file from template..."
    cp .env.example .env
    echo "✅ .env file created. Please edit it with your configuration."
    echo "📝 Run: nano .env"
    exit 0
fi

# Validate environment
echo "🔍 Validating environment configuration..."
./scripts/validate-env.sh

# Start databases with Docker
echo "🐳 Starting database services..."
docker-compose up -d postgres redis

# Wait for databases to be ready
echo "⏳ Waiting for databases to be ready..."
sleep 10

# Check database connectivity
echo "🔌 Testing database connectivity..."
export $(grep -v '^#' .env | xargs)

# Test PostgreSQL
if command -v psql &> /dev/null; then
    PGPASSWORD=$DB_PASSWORD psql -h $DB_HOST -p $DB_PORT -U $DB_USERNAME -d $DB_NAME -c "SELECT 1;" > /dev/null
    echo "✅ PostgreSQL connection successful"
else
    echo "⚠️  psql not installed, skipping PostgreSQL test"
fi

# Test Redis
if command -v redis-cli &> /dev/null; then
    redis-cli -h $REDIS_HOST -p $REDIS_PORT -a $REDIS_PASSWORD ping > /dev/null
    echo "✅ Redis connection successful"
else
    echo "⚠️  redis-cli not installed, skipping Redis test"
fi

echo "🎉 Development environment setup completed!"
echo "🚀 You can now run: mvn spring-boot:run"
```

### Step 17: Make Scripts Executable

```bash
chmod +x scripts/validate-env.sh
chmod +x scripts/setup-dev.sh
```

### Example 1: First Time Setup
```bash
# Clone repository
git clone https://github.com/harshal5-dev/cloud-kart.git
cd cloud-kart

# Setup development environment
./scripts/setup-dev.sh

# Edit .env file with your configuration
nano .env

# Validate configuration
./scripts/validate-env.sh

# Run the application
mvn spring-boot:run
```

### Example 2: Docker Development
```bash
# Start all services
docker-compose up --build

# Or start databases only and run Spring Boot locally
docker-compose up -d postgres redis
mvn spring-boot:run
```

### Example 3: Production Deployment
```bash
# Create production environment
cp .env.example .env.prod
# Edit .env.prod with production values

# Deploy
docker-compose -f docker-compose.yml -f docker-compose.prod.yml --env-file .env.prod up -d

# Monitor
docker-compose logs -f
```

This comprehensive guide covers everything you need to integrate `.env` files with your Spring Boot microservices and Docker containers, providing a robust and secure configuration management solution for your Cloud Kart e-commerce platform.
